### PR TITLE
docker-compose: Always use latest Jesse release image

### PR DESCRIPTION
**Pull request by TheCrazyLex**

### CODE REVIEW

**Comment by TheCrazyLex** [comment]
Hi @julesGoullee and @saleh-mir,

I don't really see a reason to always manually update the version tag in this repo.
If there is actually a reason, let's discuss it here :)

Thanks!

**Comment by julesGoullee** [comment]
> Hi @julesGoullee and @saleh-mir,
> 
> I don't really see a reason to always manually update the version tag in this repo.
> If there is actually a reason, let's discuss it here :)
> 
> Thanks!

Yeah will be definitely more comfortable to maintain the repository with `latest` tag. This is not a good practice. Someone pulls locally latest version we can't be sure they have to use the 'latest' latest, may be an outdated one. Or another case, the real latest version is not compatible anymore with the setup here, then will lead to error. In general, never set up use the latest tag, always specify the version, to make sure about the code you're running. One article that explains a bit the problem here https://vsupalov.com/docker-latest-tag/#latest-is-not-descriptive-and-hard-to-work-with.

**Comment by TheCrazyLex** [comment]
Hi @julesGoullee,

I see, that makes sense.

How would you feel about replacing the specific version with something like <PUT_JESSE_VERSION_HERE> and documenting that you have to put in the version in the README?

Alternatively there is also the possibility of creating a github action which periodically checks docker and opens a pull request putting in the new version when needed.

All in all I would really like to make sure that a new user of this repository never starts with an outdated version of jesse, as is the case right now, while minimizing maintenence time.

**Comment by saleh-mir** [comment]
> How would you feel about replacing the specific version with something like <PUT_JESSE_VERSION_HERE> and documenting that you have to put in the version in the README?

> Alternatively there is also the possibility of creating a github action which periodically checks docker and opens a pull request putting in the new version when needed.


As one of the maintainers, I'm very much in favor of either to minis the maintenence time.

**Comment by julesGoullee** [comment]
Obviously like you guys I want to minimize the maintenance tasks. I'm ok to go with the latest for the reason that it keep a 'ready to work' file and don't required any modification to be good to go, in opposite of <PUT_JESSE_VERSION_HERE> option. I will merged this or then

**Comment by julesGoullee** [comment]
@TheCrazyLex can you please also update the doc docker page to reflect this changed and also used the latest tag? thx

**Comment by TheCrazyLex** [comment]
@julesGoullee Thanks. Will do

**Pull request merged**
